# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow8.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 956)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 941))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setBaseSize(QtCore.QSize(799, 600))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelTodayDate = QtWidgets.QLabel(self.tab)
        self.labelTodayDate.setGeometry(QtCore.QRect(210, 50, 89, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTodayDate.setFont(font)
        self.labelTodayDate.setText("")
        self.labelTodayDate.setObjectName("labelTodayDate")
        self.lineEditSymbol = QtWidgets.QLineEdit(self.tab)
        self.lineEditSymbol.setEnabled(True)
        self.lineEditSymbol.setGeometry(QtCore.QRect(336, 30, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSymbol.sizePolicy().hasHeightForWidth())
        self.lineEditSymbol.setSizePolicy(sizePolicy)
        self.lineEditSymbol.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditSymbol.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSymbol.setFont(font)
        self.lineEditSymbol.setObjectName("lineEditSymbol")
        self.labelSymbol = QtWidgets.QLabel(self.tab)
        self.labelSymbol.setEnabled(True)
        self.labelSymbol.setGeometry(QtCore.QRect(210, 10, 120, 40))
        self.labelSymbol.setMinimumSize(QtCore.QSize(120, 40))
        self.labelSymbol.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelSymbol.setFont(font)
        self.labelSymbol.setText("")
        self.labelSymbol.setObjectName("labelSymbol")
        self.pushButtonACD = QtWidgets.QPushButton(self.tab)
        self.pushButtonACD.setGeometry(QtCore.QRect(560, 20, 120, 48))
        self.pushButtonACD.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACD.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACD.setObjectName("pushButtonACD")
        self.lineEditOpenRangeHigh = QtWidgets.QLineEdit(self.tab)
        self.lineEditOpenRangeHigh.setEnabled(True)
        self.lineEditOpenRangeHigh.setGeometry(QtCore.QRect(50, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOpenRangeHigh.sizePolicy().hasHeightForWidth())
        self.lineEditOpenRangeHigh.setSizePolicy(sizePolicy)
        self.lineEditOpenRangeHigh.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditOpenRangeHigh.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOpenRangeHigh.setFont(font)
        self.lineEditOpenRangeHigh.setText("")
        self.lineEditOpenRangeHigh.setObjectName("lineEditOpenRangeHigh")
        self.labelOpenRangeHigh = QtWidgets.QLabel(self.tab)
        self.labelOpenRangeHigh.setEnabled(True)
        self.labelOpenRangeHigh.setGeometry(QtCore.QRect(110, 300, 120, 40))
        self.labelOpenRangeHigh.setMinimumSize(QtCore.QSize(120, 40))
        self.labelOpenRangeHigh.setBaseSize(QtCore.QSize(120, 40))
        self.labelOpenRangeHigh.setObjectName("labelOpenRangeHigh")
        self.labelOpenRangeLow = QtWidgets.QLabel(self.tab)
        self.labelOpenRangeLow.setEnabled(True)
        self.labelOpenRangeLow.setGeometry(QtCore.QRect(390, 300, 120, 40))
        self.labelOpenRangeLow.setMinimumSize(QtCore.QSize(120, 40))
        self.labelOpenRangeLow.setBaseSize(QtCore.QSize(120, 40))
        self.labelOpenRangeLow.setObjectName("labelOpenRangeLow")
        self.lineEditOpenRangeLow = QtWidgets.QLineEdit(self.tab)
        self.lineEditOpenRangeLow.setEnabled(True)
        self.lineEditOpenRangeLow.setGeometry(QtCore.QRect(330, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOpenRangeLow.sizePolicy().hasHeightForWidth())
        self.lineEditOpenRangeLow.setSizePolicy(sizePolicy)
        self.lineEditOpenRangeLow.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditOpenRangeLow.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOpenRangeLow.setFont(font)
        self.lineEditOpenRangeLow.setText("")
        self.lineEditOpenRangeLow.setObjectName("lineEditOpenRangeLow")
        self.lineEditDailyPivotNumber = QtWidgets.QLineEdit(self.tab)
        self.lineEditDailyPivotNumber.setEnabled(True)
        self.lineEditDailyPivotNumber.setGeometry(QtCore.QRect(570, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDailyPivotNumber.sizePolicy().hasHeightForWidth())
        self.lineEditDailyPivotNumber.setSizePolicy(sizePolicy)
        self.lineEditDailyPivotNumber.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditDailyPivotNumber.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditDailyPivotNumber.setFont(font)
        self.lineEditDailyPivotNumber.setText("")
        self.lineEditDailyPivotNumber.setObjectName("lineEditDailyPivotNumber")
        self.labelDailyPivotNumber = QtWidgets.QLabel(self.tab)
        self.labelDailyPivotNumber.setEnabled(True)
        self.labelDailyPivotNumber.setGeometry(QtCore.QRect(620, 300, 120, 40))
        self.labelDailyPivotNumber.setMinimumSize(QtCore.QSize(120, 40))
        self.labelDailyPivotNumber.setBaseSize(QtCore.QSize(120, 40))
        self.labelDailyPivotNumber.setObjectName("labelDailyPivotNumber")
        self.labelAup = QtWidgets.QLabel(self.tab)
        self.labelAup.setEnabled(True)
        self.labelAup.setGeometry(QtCore.QRect(130, 410, 120, 40))
        self.labelAup.setMinimumSize(QtCore.QSize(120, 40))
        self.labelAup.setBaseSize(QtCore.QSize(120, 40))
        self.labelAup.setObjectName("labelAup")
        self.lineEditAup = QtWidgets.QLineEdit(self.tab)
        self.lineEditAup.setEnabled(True)
        self.lineEditAup.setGeometry(QtCore.QRect(40, 440, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAup.sizePolicy().hasHeightForWidth())
        self.lineEditAup.setSizePolicy(sizePolicy)
        self.lineEditAup.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditAup.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAup.setFont(font)
        self.lineEditAup.setText("")
        self.lineEditAup.setObjectName("lineEditAup")
        self.labelAdwn = QtWidgets.QLabel(self.tab)
        self.labelAdwn.setEnabled(True)
        self.labelAdwn.setGeometry(QtCore.QRect(360, 410, 120, 40))
        self.labelAdwn.setMinimumSize(QtCore.QSize(120, 40))
        self.labelAdwn.setBaseSize(QtCore.QSize(120, 40))
        self.labelAdwn.setObjectName("labelAdwn")
        self.lineEditAdwn = QtWidgets.QLineEdit(self.tab)
        self.lineEditAdwn.setEnabled(True)
        self.lineEditAdwn.setGeometry(QtCore.QRect(330, 450, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAdwn.sizePolicy().hasHeightForWidth())
        self.lineEditAdwn.setSizePolicy(sizePolicy)
        self.lineEditAdwn.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditAdwn.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAdwn.setFont(font)
        self.lineEditAdwn.setText("")
        self.lineEditAdwn.setObjectName("lineEditAdwn")
        self.lineEditTone = QtWidgets.QLineEdit(self.tab)
        self.lineEditTone.setEnabled(True)
        self.lineEditTone.setGeometry(QtCore.QRect(570, 450, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTone.sizePolicy().hasHeightForWidth())
        self.lineEditTone.setSizePolicy(sizePolicy)
        self.lineEditTone.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditTone.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditTone.setFont(font)
        self.lineEditTone.setText("")
        self.lineEditTone.setObjectName("lineEditTone")
        self.labelTone = QtWidgets.QLabel(self.tab)
        self.labelTone.setEnabled(True)
        self.labelTone.setGeometry(QtCore.QRect(620, 410, 120, 40))
        self.labelTone.setMinimumSize(QtCore.QSize(120, 40))
        self.labelTone.setBaseSize(QtCore.QSize(120, 40))
        self.labelTone.setObjectName("labelTone")
        self.labelPivotRangeTop = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop.setEnabled(True)
        self.labelPivotRangeTop.setGeometry(QtCore.QRect(90, 500, 120, 40))
        self.labelPivotRangeTop.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop.setObjectName("labelPivotRangeTop")
        self.lineEditPivotRangeTop = QtWidgets.QLineEdit(self.tab)
        self.lineEditPivotRangeTop.setEnabled(True)
        self.lineEditPivotRangeTop.setGeometry(QtCore.QRect(40, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPivotRangeTop.sizePolicy().hasHeightForWidth())
        self.lineEditPivotRangeTop.setSizePolicy(sizePolicy)
        self.lineEditPivotRangeTop.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditPivotRangeTop.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPivotRangeTop.setFont(font)
        self.lineEditPivotRangeTop.setText("")
        self.lineEditPivotRangeTop.setObjectName("lineEditPivotRangeTop")
        self.labelPivotRangeBottom = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeBottom.setEnabled(True)
        self.labelPivotRangeBottom.setGeometry(QtCore.QRect(360, 510, 120, 40))
        self.labelPivotRangeBottom.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeBottom.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeBottom.setObjectName("labelPivotRangeBottom")
        self.lineEditPivotRangeBottom = QtWidgets.QLineEdit(self.tab)
        self.lineEditPivotRangeBottom.setEnabled(True)
        self.lineEditPivotRangeBottom.setGeometry(QtCore.QRect(330, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPivotRangeBottom.sizePolicy().hasHeightForWidth())
        self.lineEditPivotRangeBottom.setSizePolicy(sizePolicy)
        self.lineEditPivotRangeBottom.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditPivotRangeBottom.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPivotRangeBottom.setFont(font)
        self.lineEditPivotRangeBottom.setText("")
        self.lineEditPivotRangeBottom.setObjectName("lineEditPivotRangeBottom")
        self.lineEditLastOpen = QtWidgets.QLineEdit(self.tab)
        self.lineEditLastOpen.setEnabled(True)
        self.lineEditLastOpen.setGeometry(QtCore.QRect(40, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLastOpen.sizePolicy().hasHeightForWidth())
        self.lineEditLastOpen.setSizePolicy(sizePolicy)
        self.lineEditLastOpen.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditLastOpen.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLastOpen.setFont(font)
        self.lineEditLastOpen.setText("")
        self.lineEditLastOpen.setObjectName("lineEditLastOpen")
        self.lineEditLastClose = QtWidgets.QLineEdit(self.tab)
        self.lineEditLastClose.setEnabled(True)
        self.lineEditLastClose.setGeometry(QtCore.QRect(330, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLastClose.sizePolicy().hasHeightForWidth())
        self.lineEditLastClose.setSizePolicy(sizePolicy)
        self.lineEditLastClose.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditLastClose.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLastClose.setFont(font)
        self.lineEditLastClose.setText("")
        self.lineEditLastClose.setObjectName("lineEditLastClose")
        self.labelPivotRangeTop_2 = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop_2.setEnabled(True)
        self.labelPivotRangeTop_2.setGeometry(QtCore.QRect(90, 590, 120, 40))
        self.labelPivotRangeTop_2.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_2.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_2.setObjectName("labelPivotRangeTop_2")
        self.labelPivotRangeTop_3 = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop_3.setEnabled(True)
        self.labelPivotRangeTop_3.setGeometry(QtCore.QRect(370, 590, 120, 40))
        self.labelPivotRangeTop_3.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_3.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_3.setObjectName("labelPivotRangeTop_3")
        self.lineEditMomentum = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentum.setEnabled(True)
        self.lineEditMomentum.setGeometry(QtCore.QRect(560, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentum.sizePolicy().hasHeightForWidth())
        self.lineEditMomentum.setSizePolicy(sizePolicy)
        self.lineEditMomentum.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentum.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentum.setFont(font)
        self.lineEditMomentum.setText("")
        self.lineEditMomentum.setObjectName("lineEditMomentum")
        self.labelMomentum = QtWidgets.QLabel(self.tab)
        self.labelMomentum.setEnabled(True)
        self.labelMomentum.setGeometry(QtCore.QRect(620, 500, 120, 40))
        self.labelMomentum.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentum.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentum.setObjectName("labelMomentum")
        self.labelMomentumYesterday2 = QtWidgets.QLabel(self.tab)
        self.labelMomentumYesterday2.setEnabled(True)
        self.labelMomentumYesterday2.setGeometry(QtCore.QRect(620, 600, 120, 40))
        self.labelMomentumYesterday2.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday2.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday2.setObjectName("labelMomentumYesterday2")
        self.lineEditMomentumYesterday2 = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentumYesterday2.setEnabled(True)
        self.lineEditMomentumYesterday2.setGeometry(QtCore.QRect(560, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentumYesterday2.sizePolicy().hasHeightForWidth())
        self.lineEditMomentumYesterday2.setSizePolicy(sizePolicy)
        self.lineEditMomentumYesterday2.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentumYesterday2.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentumYesterday2.setFont(font)
        self.lineEditMomentumYesterday2.setText("")
        self.lineEditMomentumYesterday2.setObjectName("lineEditMomentumYesterday2")
        self.labelMomentumYesterday3 = QtWidgets.QLabel(self.tab)
        self.labelMomentumYesterday3.setEnabled(True)
        self.labelMomentumYesterday3.setGeometry(QtCore.QRect(610, 690, 120, 40))
        self.labelMomentumYesterday3.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday3.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday3.setObjectName("labelMomentumYesterday3")
        self.lineEditMomentumYesterday3 = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentumYesterday3.setEnabled(True)
        self.lineEditMomentumYesterday3.setGeometry(QtCore.QRect(560, 730, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentumYesterday3.sizePolicy().hasHeightForWidth())
        self.lineEditMomentumYesterday3.setSizePolicy(sizePolicy)
        self.lineEditMomentumYesterday3.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentumYesterday3.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentumYesterday3.setFont(font)
        self.lineEditMomentumYesterday3.setText("")
        self.lineEditMomentumYesterday3.setObjectName("lineEditMomentumYesterday3")
        self.lineEdit10mintdypivot = QtWidgets.QLineEdit(self.tab)
        self.lineEdit10mintdypivot.setEnabled(True)
        self.lineEdit10mintdypivot.setGeometry(QtCore.QRect(330, 210, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit10mintdypivot.sizePolicy().hasHeightForWidth())
        self.lineEdit10mintdypivot.setSizePolicy(sizePolicy)
        self.lineEdit10mintdypivot.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEdit10mintdypivot.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit10mintdypivot.setFont(font)
        self.lineEdit10mintdypivot.setText("")
        self.lineEdit10mintdypivot.setObjectName("lineEdit10mintdypivot")
        self.labelNowPivotTen = QtWidgets.QLabel(self.tab)
        self.labelNowPivotTen.setEnabled(True)
        self.labelNowPivotTen.setGeometry(QtCore.QRect(390, 170, 120, 40))
        self.labelNowPivotTen.setMinimumSize(QtCore.QSize(120, 40))
        self.labelNowPivotTen.setBaseSize(QtCore.QSize(120, 40))
        self.labelNowPivotTen.setObjectName("labelNowPivotTen")
        self.lineEditRelativeVolume = QtWidgets.QLineEdit(self.tab)
        self.lineEditRelativeVolume.setEnabled(True)
        self.lineEditRelativeVolume.setGeometry(QtCore.QRect(560, 210, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRelativeVolume.sizePolicy().hasHeightForWidth())
        self.lineEditRelativeVolume.setSizePolicy(sizePolicy)
        self.lineEditRelativeVolume.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditRelativeVolume.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRelativeVolume.setFont(font)
        self.lineEditRelativeVolume.setText("")
        self.lineEditRelativeVolume.setObjectName("lineEditRelativeVolume")
        self.labelVolume = QtWidgets.QLabel(self.tab)
        self.labelVolume.setEnabled(True)
        self.labelVolume.setGeometry(QtCore.QRect(610, 170, 120, 40))
        self.labelVolume.setMinimumSize(QtCore.QSize(120, 40))
        self.labelVolume.setBaseSize(QtCore.QSize(120, 40))
        self.labelVolume.setObjectName("labelVolume")
        self.pushButtonMacroPlot = QtWidgets.QPushButton(self.tab)
        self.pushButtonMacroPlot.setGeometry(QtCore.QRect(700, 20, 60, 48))
        self.pushButtonMacroPlot.setMinimumSize(QtCore.QSize(60, 48))
        self.pushButtonMacroPlot.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonMacroPlot.setObjectName("pushButtonMacroPlot")
        self.pushButtonMacroCreate = QtWidgets.QPushButton(self.tab)
        self.pushButtonMacroCreate.setEnabled(False)
        self.pushButtonMacroCreate.setGeometry(QtCore.QRect(700, 80, 60, 48))
        self.pushButtonMacroCreate.setMinimumSize(QtCore.QSize(60, 48))
        self.pushButtonMacroCreate.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonMacroCreate.setObjectName("pushButtonMacroCreate")
        self.pushButtonAddAlert = QtWidgets.QPushButton(self.tab)
        self.pushButtonAddAlert.setGeometry(QtCore.QRect(130, 30, 60, 48))
        self.pushButtonAddAlert.setMinimumSize(QtCore.QSize(60, 48))
        self.pushButtonAddAlert.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAddAlert.setObjectName("pushButtonAddAlert")
        self.tableWidgetEvent = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetEvent.setGeometry(QtCore.QRect(30, 100, 256, 192))
        self.tableWidgetEvent.setObjectName("tableWidgetEvent")
        self.tableWidgetEvent.setColumnCount(3)
        self.tableWidgetEvent.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEvent.setHorizontalHeaderItem(2, item)
        self.pushButtonGetAlertPlot = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetAlertPlot.setGeometry(QtCore.QRect(40, 30, 60, 48))
        self.pushButtonGetAlertPlot.setMinimumSize(QtCore.QSize(60, 48))
        self.pushButtonGetAlertPlot.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonGetAlertPlot.setObjectName("pushButtonGetAlertPlot")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(40, 690, 321, 191))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 10, 122, 158))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandLinkButtonAddAlertAup2 = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButtonAddAlertAup2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAup2.setFont(font)
        self.commandLinkButtonAddAlertAup2.setText("")
        self.commandLinkButtonAddAlertAup2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup2.setObjectName("commandLinkButtonAddAlertAup2")
        self.verticalLayout_2.addWidget(self.commandLinkButtonAddAlertAup2)
        self.commandLinkButtonAddAlertAup4 = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButtonAddAlertAup4.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup4.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAup4.setFont(font)
        self.commandLinkButtonAddAlertAup4.setText("")
        self.commandLinkButtonAddAlertAup4.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup4.setObjectName("commandLinkButtonAddAlertAup4")
        self.verticalLayout_2.addWidget(self.commandLinkButtonAddAlertAup4)
        self.commandLinkButtonAddAlertAup6 = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButtonAddAlertAup6.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup6.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAup6.setFont(font)
        self.commandLinkButtonAddAlertAup6.setText("")
        self.commandLinkButtonAddAlertAup6.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup6.setObjectName("commandLinkButtonAddAlertAup6")
        self.verticalLayout_2.addWidget(self.commandLinkButtonAddAlertAup6)
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setGeometry(QtCore.QRect(0, 10, 122, 158))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandLinkButtonAddAlertAup1 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButtonAddAlertAup1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAup1.setFont(font)
        self.commandLinkButtonAddAlertAup1.setText("")
        self.commandLinkButtonAddAlertAup1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup1.setObjectName("commandLinkButtonAddAlertAup1")
        self.verticalLayout.addWidget(self.commandLinkButtonAddAlertAup1)
        self.commandLinkButtonAddAlertAup3 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButtonAddAlertAup3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAup3.setFont(font)
        self.commandLinkButtonAddAlertAup3.setText("")
        self.commandLinkButtonAddAlertAup3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup3.setObjectName("commandLinkButtonAddAlertAup3")
        self.verticalLayout.addWidget(self.commandLinkButtonAddAlertAup3)
        self.commandLinkButtonAddAlertAup5 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButtonAddAlertAup5.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAup5.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAup5.setFont(font)
        self.commandLinkButtonAddAlertAup5.setText("")
        self.commandLinkButtonAddAlertAup5.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAup5.setObjectName("commandLinkButtonAddAlertAup5")
        self.verticalLayout.addWidget(self.commandLinkButtonAddAlertAup5)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget_2.setGeometry(QtCore.QRect(80, 10, 122, 158))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandLinkButtonAddAlertCup1 = QtWidgets.QCommandLinkButton(self.layoutWidget_2)
        self.commandLinkButtonAddAlertCup1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCup1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertCup1.setFont(font)
        self.commandLinkButtonAddAlertCup1.setText("")
        self.commandLinkButtonAddAlertCup1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCup1.setObjectName("commandLinkButtonAddAlertCup1")
        self.verticalLayout_3.addWidget(self.commandLinkButtonAddAlertCup1)
        self.commandLinkButtonAddAlertCup2 = QtWidgets.QCommandLinkButton(self.layoutWidget_2)
        self.commandLinkButtonAddAlertCup2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCup2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertCup2.setFont(font)
        self.commandLinkButtonAddAlertCup2.setText("")
        self.commandLinkButtonAddAlertCup2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCup2.setObjectName("commandLinkButtonAddAlertCup2")
        self.verticalLayout_3.addWidget(self.commandLinkButtonAddAlertCup2)
        self.commandLinkButtonAddAlertCup3 = QtWidgets.QCommandLinkButton(self.layoutWidget_2)
        self.commandLinkButtonAddAlertCup3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCup3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertCup3.setFont(font)
        self.commandLinkButtonAddAlertCup3.setText("")
        self.commandLinkButtonAddAlertCup3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCup3.setObjectName("commandLinkButtonAddAlertCup3")
        self.verticalLayout_3.addWidget(self.commandLinkButtonAddAlertCup3)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 10, 122, 158))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commandLinkButtonAddAlertAdwn1 = QtWidgets.QCommandLinkButton(self.layoutWidget_3)
        self.commandLinkButtonAddAlertAdwn1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAdwn1.setFont(font)
        self.commandLinkButtonAddAlertAdwn1.setText("")
        self.commandLinkButtonAddAlertAdwn1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn1.setObjectName("commandLinkButtonAddAlertAdwn1")
        self.verticalLayout_4.addWidget(self.commandLinkButtonAddAlertAdwn1)
        self.commandLinkButtonAddAlertAdwn3 = QtWidgets.QCommandLinkButton(self.layoutWidget_3)
        self.commandLinkButtonAddAlertAdwn3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwn3.setFont(font)
        self.commandLinkButtonAddAlertAdwn3.setText("")
        self.commandLinkButtonAddAlertAdwn3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn3.setObjectName("commandLinkButtonAddAlertAdwn3")
        self.verticalLayout_4.addWidget(self.commandLinkButtonAddAlertAdwn3)
        self.commandLinkButtonAddAlertAdwn5 = QtWidgets.QCommandLinkButton(self.layoutWidget_3)
        self.commandLinkButtonAddAlertAdwn5.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn5.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwn5.setFont(font)
        self.commandLinkButtonAddAlertAdwn5.setText("")
        self.commandLinkButtonAddAlertAdwn5.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn5.setObjectName("commandLinkButtonAddAlertAdwn5")
        self.verticalLayout_4.addWidget(self.commandLinkButtonAddAlertAdwn5)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(150, 10, 122, 158))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.commandLinkButtonAddAlertAdwn2 = QtWidgets.QCommandLinkButton(self.layoutWidget_4)
        self.commandLinkButtonAddAlertAdwn2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAdwn2.setFont(font)
        self.commandLinkButtonAddAlertAdwn2.setText("")
        self.commandLinkButtonAddAlertAdwn2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn2.setObjectName("commandLinkButtonAddAlertAdwn2")
        self.verticalLayout_5.addWidget(self.commandLinkButtonAddAlertAdwn2)
        self.commandLinkButtonAddAlertAdwn4 = QtWidgets.QCommandLinkButton(self.layoutWidget_4)
        self.commandLinkButtonAddAlertAdwn4.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn4.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwn4.setFont(font)
        self.commandLinkButtonAddAlertAdwn4.setText("")
        self.commandLinkButtonAddAlertAdwn4.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn4.setObjectName("commandLinkButtonAddAlertAdwn4")
        self.verticalLayout_5.addWidget(self.commandLinkButtonAddAlertAdwn4)
        self.commandLinkButtonAddAlertAdwn6 = QtWidgets.QCommandLinkButton(self.layoutWidget_4)
        self.commandLinkButtonAddAlertAdwn6.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwn6.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwn6.setFont(font)
        self.commandLinkButtonAddAlertAdwn6.setText("")
        self.commandLinkButtonAddAlertAdwn6.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwn6.setObjectName("commandLinkButtonAddAlertAdwn6")
        self.verticalLayout_5.addWidget(self.commandLinkButtonAddAlertAdwn6)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_9.setGeometry(QtCore.QRect(80, 10, 122, 158))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.commandLinkButtonAddAlertCdwn1 = QtWidgets.QCommandLinkButton(self.layoutWidget_9)
        self.commandLinkButtonAddAlertCdwn1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCdwn1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertCdwn1.setFont(font)
        self.commandLinkButtonAddAlertCdwn1.setText("")
        self.commandLinkButtonAddAlertCdwn1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCdwn1.setObjectName("commandLinkButtonAddAlertCdwn1")
        self.verticalLayout_10.addWidget(self.commandLinkButtonAddAlertCdwn1)
        self.commandLinkButtonAddAlertCdwn2 = QtWidgets.QCommandLinkButton(self.layoutWidget_9)
        self.commandLinkButtonAddAlertCdwn2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCdwn2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertCdwn2.setFont(font)
        self.commandLinkButtonAddAlertCdwn2.setText("")
        self.commandLinkButtonAddAlertCdwn2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCdwn2.setObjectName("commandLinkButtonAddAlertCdwn2")
        self.verticalLayout_10.addWidget(self.commandLinkButtonAddAlertCdwn2)
        self.commandLinkButtonAddAlertCdwn3 = QtWidgets.QCommandLinkButton(self.layoutWidget_9)
        self.commandLinkButtonAddAlertCdwn3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertCdwn3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertCdwn3.setFont(font)
        self.commandLinkButtonAddAlertCdwn3.setText("")
        self.commandLinkButtonAddAlertCdwn3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertCdwn3.setObjectName("commandLinkButtonAddAlertCdwn3")
        self.verticalLayout_10.addWidget(self.commandLinkButtonAddAlertCdwn3)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 10, 122, 158))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.commandLinkButtonAddAlertAupfail1 = QtWidgets.QCommandLinkButton(self.layoutWidget_7)
        self.commandLinkButtonAddAlertAupfail1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAupfail1.setFont(font)
        self.commandLinkButtonAddAlertAupfail1.setText("")
        self.commandLinkButtonAddAlertAupfail1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail1.setObjectName("commandLinkButtonAddAlertAupfail1")
        self.verticalLayout_8.addWidget(self.commandLinkButtonAddAlertAupfail1)
        self.commandLinkButtonAddAlertAupfail3 = QtWidgets.QCommandLinkButton(self.layoutWidget_7)
        self.commandLinkButtonAddAlertAupfail3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAupfail3.setFont(font)
        self.commandLinkButtonAddAlertAupfail3.setText("")
        self.commandLinkButtonAddAlertAupfail3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail3.setObjectName("commandLinkButtonAddAlertAupfail3")
        self.verticalLayout_8.addWidget(self.commandLinkButtonAddAlertAupfail3)
        self.commandLinkButtonAddAlertAupfail5 = QtWidgets.QCommandLinkButton(self.layoutWidget_7)
        self.commandLinkButtonAddAlertAupfail5.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail5.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAupfail5.setFont(font)
        self.commandLinkButtonAddAlertAupfail5.setText("")
        self.commandLinkButtonAddAlertAupfail5.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail5.setObjectName("commandLinkButtonAddAlertAupfail5")
        self.verticalLayout_8.addWidget(self.commandLinkButtonAddAlertAupfail5)
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget_8.setGeometry(QtCore.QRect(150, 10, 122, 158))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.commandLinkButtonAddAlertAupfail2 = QtWidgets.QCommandLinkButton(self.layoutWidget_8)
        self.commandLinkButtonAddAlertAupfail2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAupfail2.setFont(font)
        self.commandLinkButtonAddAlertAupfail2.setText("")
        self.commandLinkButtonAddAlertAupfail2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail2.setObjectName("commandLinkButtonAddAlertAupfail2")
        self.verticalLayout_9.addWidget(self.commandLinkButtonAddAlertAupfail2)
        self.commandLinkButtonAddAlertAupfail4 = QtWidgets.QCommandLinkButton(self.layoutWidget_8)
        self.commandLinkButtonAddAlertAupfail4.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail4.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAupfail4.setFont(font)
        self.commandLinkButtonAddAlertAupfail4.setText("")
        self.commandLinkButtonAddAlertAupfail4.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail4.setObjectName("commandLinkButtonAddAlertAupfail4")
        self.verticalLayout_9.addWidget(self.commandLinkButtonAddAlertAupfail4)
        self.commandLinkButtonAddAlertAupfail6 = QtWidgets.QCommandLinkButton(self.layoutWidget_8)
        self.commandLinkButtonAddAlertAupfail6.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAupfail6.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAupfail6.setFont(font)
        self.commandLinkButtonAddAlertAupfail6.setText("")
        self.commandLinkButtonAddAlertAupfail6.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAupfail6.setObjectName("commandLinkButtonAddAlertAupfail6")
        self.verticalLayout_9.addWidget(self.commandLinkButtonAddAlertAupfail6)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 10, 122, 158))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.commandLinkButtonAddAlertAdwnfail1 = QtWidgets.QCommandLinkButton(self.layoutWidget_5)
        self.commandLinkButtonAddAlertAdwnfail1.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail1.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAdwnfail1.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail1.setText("")
        self.commandLinkButtonAddAlertAdwnfail1.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail1.setObjectName("commandLinkButtonAddAlertAdwnfail1")
        self.verticalLayout_6.addWidget(self.commandLinkButtonAddAlertAdwnfail1)
        self.commandLinkButtonAddAlertAdwnfail3 = QtWidgets.QCommandLinkButton(self.layoutWidget_5)
        self.commandLinkButtonAddAlertAdwnfail3.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail3.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwnfail3.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail3.setText("")
        self.commandLinkButtonAddAlertAdwnfail3.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail3.setObjectName("commandLinkButtonAddAlertAdwnfail3")
        self.verticalLayout_6.addWidget(self.commandLinkButtonAddAlertAdwnfail3)
        self.commandLinkButtonAddAlertAdwnfail5 = QtWidgets.QCommandLinkButton(self.layoutWidget_5)
        self.commandLinkButtonAddAlertAdwnfail5.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail5.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwnfail5.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail5.setText("")
        self.commandLinkButtonAddAlertAdwnfail5.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail5.setObjectName("commandLinkButtonAddAlertAdwnfail5")
        self.verticalLayout_6.addWidget(self.commandLinkButtonAddAlertAdwnfail5)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget_6.setGeometry(QtCore.QRect(150, 10, 122, 158))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.commandLinkButtonAddAlertAdwnfail2 = QtWidgets.QCommandLinkButton(self.layoutWidget_6)
        self.commandLinkButtonAddAlertAdwnfail2.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail2.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButtonAddAlertAdwnfail2.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail2.setText("")
        self.commandLinkButtonAddAlertAdwnfail2.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail2.setObjectName("commandLinkButtonAddAlertAdwnfail2")
        self.verticalLayout_7.addWidget(self.commandLinkButtonAddAlertAdwnfail2)
        self.commandLinkButtonAddAlertAdwnfail4 = QtWidgets.QCommandLinkButton(self.layoutWidget_6)
        self.commandLinkButtonAddAlertAdwnfail4.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail4.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwnfail4.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail4.setText("")
        self.commandLinkButtonAddAlertAdwnfail4.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail4.setObjectName("commandLinkButtonAddAlertAdwnfail4")
        self.verticalLayout_7.addWidget(self.commandLinkButtonAddAlertAdwnfail4)
        self.commandLinkButtonAddAlertAdwnfail6 = QtWidgets.QCommandLinkButton(self.layoutWidget_6)
        self.commandLinkButtonAddAlertAdwnfail6.setMinimumSize(QtCore.QSize(60, 48))
        self.commandLinkButtonAddAlertAdwnfail6.setBaseSize(QtCore.QSize(120, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.commandLinkButtonAddAlertAdwnfail6.setFont(font)
        self.commandLinkButtonAddAlertAdwnfail6.setText("")
        self.commandLinkButtonAddAlertAdwnfail6.setIconSize(QtCore.QSize(0, 0))
        self.commandLinkButtonAddAlertAdwnfail6.setObjectName("commandLinkButtonAddAlertAdwnfail6")
        self.verticalLayout_7.addWidget(self.commandLinkButtonAddAlertAdwnfail6)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(561, 80, 120, 40))
        self.comboBox.setMinimumSize(QtCore.QSize(120, 40))
        self.comboBox.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.lineEditBidAsk = QtWidgets.QLineEdit(self.tab)
        self.lineEditBidAsk.setEnabled(True)
        self.lineEditBidAsk.setGeometry(QtCore.QRect(330, 120, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBidAsk.sizePolicy().hasHeightForWidth())
        self.lineEditBidAsk.setSizePolicy(sizePolicy)
        self.lineEditBidAsk.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditBidAsk.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBidAsk.setFont(font)
        self.lineEditBidAsk.setText("")
        self.lineEditBidAsk.setObjectName("lineEditBidAsk")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButtonACDgetshorts = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonACDgetshorts.setGeometry(QtCore.QRect(470, 40, 120, 48))
        self.pushButtonACDgetshorts.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetshorts.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetshorts.setObjectName("pushButtonACDgetshorts")
        self.pushButtonACDgetlongs = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonACDgetlongs.setGeometry(QtCore.QRect(100, 40, 120, 48))
        self.pushButtonACDgetlongs.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetlongs.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetlongs.setObjectName("pushButtonACDgetlongs")
        self.pushButtonAuplongs = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAuplongs.setGeometry(QtCore.QRect(100, 120, 120, 48))
        self.pushButtonAuplongs.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAuplongs.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAuplongs.setObjectName("pushButtonAuplongs")
        self.pushButtonAdwnshorts = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAdwnshorts.setGeometry(QtCore.QRect(470, 130, 120, 48))
        self.pushButtonAdwnshorts.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAdwnshorts.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAdwnshorts.setObjectName("pushButtonAdwnshorts")
        self.pushButtonAplusAlerts = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAplusAlerts.setGeometry(QtCore.QRect(100, 210, 120, 48))
        self.pushButtonAplusAlerts.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAplusAlerts.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAplusAlerts.setObjectName("pushButtonAplusAlerts")
        self.pushButtongetminalertdata = QtWidgets.QPushButton(self.tab_2)
        self.pushButtongetminalertdata.setGeometry(QtCore.QRect(280, 40, 120, 48))
        self.pushButtongetminalertdata.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtongetminalertdata.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtongetminalertdata.setObjectName("pushButtongetminalertdata")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEditAddSymbol = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditAddSymbol.setEnabled(True)
        self.lineEditAddSymbol.setGeometry(QtCore.QRect(200, 30, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAddSymbol.sizePolicy().hasHeightForWidth())
        self.lineEditAddSymbol.setSizePolicy(sizePolicy)
        self.lineEditAddSymbol.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditAddSymbol.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAddSymbol.setFont(font)
        self.lineEditAddSymbol.setText("")
        self.lineEditAddSymbol.setObjectName("lineEditAddSymbol")
        self.pushButtonAddSymbol = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonAddSymbol.setGeometry(QtCore.QRect(430, 30, 120, 48))
        self.pushButtonAddSymbol.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAddSymbol.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAddSymbol.setObjectName("pushButtonAddSymbol")
        self.labelSymbolAccepted = QtWidgets.QLabel(self.tab_3)
        self.labelSymbolAccepted.setGeometry(QtCore.QRect(590, 100, 89, 40))
        self.labelSymbolAccepted.setText("")
        self.labelSymbolAccepted.setObjectName("labelSymbolAccepted")
        self.lineEditNotes = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditNotes.setEnabled(True)
        self.lineEditNotes.setGeometry(QtCore.QRect(200, 100, 351, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNotes.sizePolicy().hasHeightForWidth())
        self.lineEditNotes.setSizePolicy(sizePolicy)
        self.lineEditNotes.setMinimumSize(QtCore.QSize(180, 40))
        self.lineEditNotes.setBaseSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNotes.setFont(font)
        self.lineEditNotes.setText("")
        self.lineEditNotes.setObjectName("lineEditNotes")
        self.dateEditDeleteDate = QtWidgets.QDateEdit(self.tab_3)
        self.dateEditDeleteDate.setGeometry(QtCore.QRect(320, 160, 120, 40))
        self.dateEditDeleteDate.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditDeleteDate.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditDeleteDate.setStyleSheet("\n"
"QDateEdit{ color: red,basesize:120x48 }\n"
"")
        self.dateEditDeleteDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 15), QtCore.QTime(0, 0, 0)))
        self.dateEditDeleteDate.setMaximumDate(QtCore.QDate(2022, 1, 1))
        self.dateEditDeleteDate.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditDeleteDate.setCalendarPopup(True)
        self.dateEditDeleteDate.setDate(QtCore.QDate(2020, 7, 15))
        self.dateEditDeleteDate.setObjectName("dateEditDeleteDate")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(90, 210, 541, 411))
        self.tableWidget.setMinimumSize(QtCore.QSize(240, 300))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(41)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.pushButtonLoadData = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonLoadData.setGeometry(QtCore.QRect(290, 640, 120, 48))
        self.pushButtonLoadData.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonLoadData.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonLoadData.setObjectName("pushButtonLoadData")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButtonCreateMacro = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonCreateMacro.setGeometry(QtCore.QRect(300, 50, 120, 48))
        self.pushButtonCreateMacro.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonCreateMacro.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonCreateMacro.setObjectName("pushButtonCreateMacro")
        self.pushButtonRetrieveMacro = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonRetrieveMacro.setGeometry(QtCore.QRect(300, 130, 120, 48))
        self.pushButtonRetrieveMacro.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonRetrieveMacro.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonRetrieveMacro.setObjectName("pushButtonRetrieveMacro")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButtonACD.clicked.connect(MainWindow.getACD)
        self.pushButtonACDgetshorts.clicked.connect(MainWindow.getminus4)
        self.pushButtonACDgetlongs.clicked.connect(MainWindow.getplus5)
        self.pushButtonAuplongs.clicked.connect(MainWindow.getauplong)
        self.pushButtonAdwnshorts.clicked.connect(MainWindow.getadwnshorts)
        self.pushButtonAddSymbol.clicked.connect(MainWindow.addsymbols)
        self.pushButtonAplusAlerts.clicked.connect(MainWindow.getaplusalerts)
        self.pushButtonCreateMacro.clicked.connect(MainWindow.createmacro)
        self.pushButtonRetrieveMacro.clicked.connect(MainWindow.retrievemacro)
        self.pushButtonLoadData.clicked.connect(MainWindow.load_initial_data)
        self.pushButtonMacroPlot.clicked.connect(MainWindow.retrieveoneplot)
        self.pushButtonMacroCreate.clicked.connect(MainWindow.getonemacro)
        self.pushButtonAddAlert.clicked.connect(MainWindow.addalertsymbol)
        self.pushButtongetminalertdata.clicked.connect(MainWindow.getminalertdata)
        self.pushButtonGetAlertPlot.clicked.connect(MainWindow.getthisplot)
        self.commandLinkButtonAddAlertAup1.clicked.connect(MainWindow.aup1)
        self.commandLinkButtonAddAlertAup2.clicked.connect(MainWindow.aup2)
        self.commandLinkButtonAddAlertAup3.clicked.connect(MainWindow.aup3)
        self.commandLinkButtonAddAlertAup4.clicked.connect(MainWindow.aup4)
        self.commandLinkButtonAddAlertAup5.clicked.connect(MainWindow.aup5)
        self.commandLinkButtonAddAlertAup6.clicked.connect(MainWindow.aup6)
        self.commandLinkButtonAddAlertCup1.clicked.connect(MainWindow.cup1)
        self.commandLinkButtonAddAlertCup2.clicked.connect(MainWindow.cup2)
        self.commandLinkButtonAddAlertCup3.clicked.connect(MainWindow.cup3)
        self.commandLinkButtonAddAlertAdwn1.clicked.connect(MainWindow.adwn1)
        self.commandLinkButtonAddAlertAdwn2.clicked.connect(MainWindow.adwn2)
        self.commandLinkButtonAddAlertAdwn3.clicked.connect(MainWindow.adwn3)
        self.commandLinkButtonAddAlertAdwn4.clicked.connect(MainWindow.adwn4)
        self.commandLinkButtonAddAlertAdwn5.clicked.connect(MainWindow.adwn5)
        self.commandLinkButtonAddAlertAdwn6.clicked.connect(MainWindow.adwn6)
        self.commandLinkButtonAddAlertAdwnfail1.clicked.connect(MainWindow.adwnfail1)
        self.commandLinkButtonAddAlertAdwnfail2.clicked.connect(MainWindow.adwnfail2)
        self.commandLinkButtonAddAlertAdwnfail3.clicked.connect(MainWindow.adwnfail3)
        self.commandLinkButtonAddAlertAdwnfail4.clicked.connect(MainWindow.adwnfail4)
        self.commandLinkButtonAddAlertAdwnfail6.clicked.connect(MainWindow.adwnfail6)
        self.commandLinkButtonAddAlertAdwnfail5.clicked.connect(MainWindow.adwnfail5)
        self.commandLinkButtonAddAlertAupfail1.clicked.connect(MainWindow.aupfail1)
        self.commandLinkButtonAddAlertAupfail2.clicked.connect(MainWindow.aupfail2)
        self.commandLinkButtonAddAlertAupfail3.clicked.connect(MainWindow.aupfail3)
        self.commandLinkButtonAddAlertAupfail4.clicked.connect(MainWindow.aupfail4)
        self.commandLinkButtonAddAlertAupfail5.clicked.connect(MainWindow.aupfail5)
        self.commandLinkButtonAddAlertAupfail6.clicked.connect(MainWindow.aupfail6)
        self.commandLinkButtonAddAlertCdwn1.clicked.connect(MainWindow.cdwn1)
        self.commandLinkButtonAddAlertCdwn3.clicked.connect(MainWindow.cdwn3)
        self.commandLinkButtonAddAlertCdwn2.clicked.connect(MainWindow.cdwn2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditSymbol, self.pushButtonACD)
        MainWindow.setTabOrder(self.pushButtonACD, self.lineEditOpenRangeHigh)
        MainWindow.setTabOrder(self.lineEditOpenRangeHigh, self.lineEditOpenRangeLow)
        MainWindow.setTabOrder(self.lineEditOpenRangeLow, self.lineEditDailyPivotNumber)
        MainWindow.setTabOrder(self.lineEditDailyPivotNumber, self.lineEditAup)
        MainWindow.setTabOrder(self.lineEditAup, self.lineEditAdwn)
        MainWindow.setTabOrder(self.lineEditAdwn, self.lineEditTone)
        MainWindow.setTabOrder(self.lineEditTone, self.lineEditPivotRangeTop)
        MainWindow.setTabOrder(self.lineEditPivotRangeTop, self.lineEditPivotRangeBottom)
        MainWindow.setTabOrder(self.lineEditPivotRangeBottom, self.lineEditLastOpen)
        MainWindow.setTabOrder(self.lineEditLastOpen, self.lineEditLastClose)
        MainWindow.setTabOrder(self.lineEditLastClose, self.lineEditMomentum)
        MainWindow.setTabOrder(self.lineEditMomentum, self.lineEditMomentumYesterday2)
        MainWindow.setTabOrder(self.lineEditMomentumYesterday2, self.lineEditMomentumYesterday3)
        MainWindow.setTabOrder(self.lineEditMomentumYesterday3, self.pushButtonACDgetshorts)
        MainWindow.setTabOrder(self.pushButtonACDgetshorts, self.pushButtonACDgetlongs)
        MainWindow.setTabOrder(self.pushButtonACDgetlongs, self.pushButtonAuplongs)
        MainWindow.setTabOrder(self.pushButtonAuplongs, self.pushButtonAdwnshorts)
        MainWindow.setTabOrder(self.pushButtonAdwnshorts, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.lineEditAddSymbol)
        MainWindow.setTabOrder(self.lineEditAddSymbol, self.lineEditNotes)
        MainWindow.setTabOrder(self.lineEditNotes, self.dateEditDeleteDate)
        MainWindow.setTabOrder(self.dateEditDeleteDate, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.pushButtonAddSymbol)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditSymbol.setText(_translate("MainWindow", "SPY"))
        self.pushButtonACD.setText(_translate("MainWindow", "Get ACD"))
        self.labelOpenRangeHigh.setText(_translate("MainWindow", "Open Range High"))
        self.labelOpenRangeLow.setText(_translate("MainWindow", "Open Range Low"))
        self.labelDailyPivotNumber.setText(_translate("MainWindow", "Daily Pivot Number"))
        self.labelAup.setText(_translate("MainWindow", "A Up "))
        self.labelAdwn.setText(_translate("MainWindow", "A Down"))
        self.labelTone.setText(_translate("MainWindow", "Tone"))
        self.labelPivotRangeTop.setText(_translate("MainWindow", "Pivot Range Top"))
        self.labelPivotRangeBottom.setText(_translate("MainWindow", "Pivot Range Bottom"))
        self.labelPivotRangeTop_2.setText(_translate("MainWindow", "Last Open"))
        self.labelPivotRangeTop_3.setText(_translate("MainWindow", "Last Close"))
        self.labelMomentum.setText(_translate("MainWindow", "Momentum 1"))
        self.labelMomentumYesterday2.setText(_translate("MainWindow", "Momentum Yesterday 2"))
        self.labelMomentumYesterday3.setText(_translate("MainWindow", "Momentum Yesterday 3"))
        self.labelNowPivotTen.setText(_translate("MainWindow", "Price as Pivot"))
        self.labelVolume.setText(_translate("MainWindow", "Relative Volume"))
        self.pushButtonMacroPlot.setText(_translate("MainWindow", "Macro Plot"))
        self.pushButtonMacroCreate.setText(_translate("MainWindow", "Macro"))
        self.pushButtonAddAlert.setText(_translate("MainWindow", "Add Alert"))
        item = self.tableWidgetEvent.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "event"))
        item = self.tableWidgetEvent.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "thistime"))
        item = self.tableWidgetEvent.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "volume"))
        self.pushButtonGetAlertPlot.setText(_translate("MainWindow", "Get Plot"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Aup"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Cup"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Adwn"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Cdwn"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "AupFail"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "AdwnFail"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Daily ACD"))
        self.pushButtonACDgetshorts.setText(_translate("MainWindow", "9:50AM - Shorts"))
        self.pushButtonACDgetlongs.setText(_translate("MainWindow", "9:50AM - Longs"))
        self.pushButtonAuplongs.setText(_translate("MainWindow", "(min) A up A dwn"))
        self.pushButtonAdwnshorts.setText(_translate("MainWindow", "(min) A up A dwn"))
        self.pushButtonAplusAlerts.setText(_translate("MainWindow", "Aup - Adwn Alerts"))
        self.pushButtongetminalertdata.setText(_translate("MainWindow", "Alert Minute Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Market"))
        self.pushButtonAddSymbol.setText(_translate("MainWindow", "Add Symbol"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "notes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "deleteday"))
        self.pushButtonLoadData.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Watch"))
        self.pushButtonCreateMacro.setText(_translate("MainWindow", "Create Macros "))
        self.pushButtonRetrieveMacro.setText(_translate("MainWindow", "Retrieve ACD Macro"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Macro"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
