# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow8.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 811))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setBaseSize(QtCore.QSize(799, 600))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelStartDate = QtWidgets.QLabel(self.tab)
        self.labelStartDate.setGeometry(QtCore.QRect(20, 190, 103, 64))
        self.labelStartDate.setObjectName("labelStartDate")
        self.labelTodayDate = QtWidgets.QLabel(self.tab)
        self.labelTodayDate.setGeometry(QtCore.QRect(280, 90, 89, 40))
        self.labelTodayDate.setObjectName("labelTodayDate")
        self.dateEditStart = QtWidgets.QDateEdit(self.tab)
        self.dateEditStart.setGeometry(QtCore.QRect(100, 210, 120, 40))
        self.dateEditStart.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditStart.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditStart.setStyleSheet("\n"
"QDateEdit{ color: red,basesize:120x48 }\n"
"")
        self.dateEditStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 6, 4), QtCore.QTime(0, 0, 0)))
        self.dateEditStart.setMaximumDate(QtCore.QDate(2022, 1, 1))
        self.dateEditStart.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditStart.setCalendarPopup(True)
        self.dateEditStart.setDate(QtCore.QDate(2020, 6, 4))
        self.dateEditStart.setObjectName("dateEditStart")
        self.dateEditToday = QtWidgets.QDateEdit(self.tab)
        self.dateEditToday.setGeometry(QtCore.QRect(370, 100, 120, 40))
        self.dateEditToday.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditToday.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditToday.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 16), QtCore.QTime(0, 0, 0)))
        self.dateEditToday.setMaximumDate(QtCore.QDate(2022, 1, 1))
        self.dateEditToday.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditToday.setCalendarPopup(True)
        self.dateEditToday.setDate(QtCore.QDate(2020, 7, 16))
        self.dateEditToday.setObjectName("dateEditToday")
        self.checkBoxToday = QtWidgets.QCheckBox(self.tab)
        self.checkBoxToday.setGeometry(QtCore.QRect(510, 100, 88, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxToday.sizePolicy().hasHeightForWidth())
        self.checkBoxToday.setSizePolicy(sizePolicy)
        self.checkBoxToday.setMinimumSize(QtCore.QSize(44, 16))
        self.checkBoxToday.setBaseSize(QtCore.QSize(44, 16))
        self.checkBoxToday.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.checkBoxToday.setAutoFillBackground(True)
        self.checkBoxToday.setStyleSheet("")
        self.checkBoxToday.setObjectName("checkBoxToday")
        self.lineEditSymbol = QtWidgets.QLineEdit(self.tab)
        self.lineEditSymbol.setEnabled(True)
        self.lineEditSymbol.setGeometry(QtCore.QRect(336, 30, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSymbol.sizePolicy().hasHeightForWidth())
        self.lineEditSymbol.setSizePolicy(sizePolicy)
        self.lineEditSymbol.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditSymbol.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSymbol.setFont(font)
        self.lineEditSymbol.setText("")
        self.lineEditSymbol.setObjectName("lineEditSymbol")
        self.labelSymbol = QtWidgets.QLabel(self.tab)
        self.labelSymbol.setEnabled(True)
        self.labelSymbol.setGeometry(QtCore.QRect(210, 30, 120, 40))
        self.labelSymbol.setMinimumSize(QtCore.QSize(120, 40))
        self.labelSymbol.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelSymbol.setFont(font)
        self.labelSymbol.setObjectName("labelSymbol")
        self.labelYesterdayDate = QtWidgets.QLabel(self.tab)
        self.labelYesterdayDate.setGeometry(QtCore.QRect(30, 80, 103, 64))
        self.labelYesterdayDate.setObjectName("labelYesterdayDate")
        self.dateEditYesterday = QtWidgets.QDateEdit(self.tab)
        self.dateEditYesterday.setGeometry(QtCore.QRect(110, 100, 120, 40))
        self.dateEditYesterday.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditYesterday.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditYesterday.setStyleSheet("\n"
"QDateEdit{ color: red,basesize:120x48 }\n"
"")
        self.dateEditYesterday.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 15), QtCore.QTime(0, 0, 0)))
        self.dateEditYesterday.setMaximumDate(QtCore.QDate(2022, 1, 1))
        self.dateEditYesterday.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditYesterday.setCalendarPopup(True)
        self.dateEditYesterday.setDate(QtCore.QDate(2020, 7, 15))
        self.dateEditYesterday.setObjectName("dateEditYesterday")
        self.pushButtonACD = QtWidgets.QPushButton(self.tab)
        self.pushButtonACD.setGeometry(QtCore.QRect(560, 20, 120, 48))
        self.pushButtonACD.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACD.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACD.setObjectName("pushButtonACD")
        self.lineEditOpenRangeHigh = QtWidgets.QLineEdit(self.tab)
        self.lineEditOpenRangeHigh.setEnabled(True)
        self.lineEditOpenRangeHigh.setGeometry(QtCore.QRect(50, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOpenRangeHigh.sizePolicy().hasHeightForWidth())
        self.lineEditOpenRangeHigh.setSizePolicy(sizePolicy)
        self.lineEditOpenRangeHigh.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditOpenRangeHigh.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOpenRangeHigh.setFont(font)
        self.lineEditOpenRangeHigh.setText("")
        self.lineEditOpenRangeHigh.setObjectName("lineEditOpenRangeHigh")
        self.labelOpenRangeHigh = QtWidgets.QLabel(self.tab)
        self.labelOpenRangeHigh.setEnabled(True)
        self.labelOpenRangeHigh.setGeometry(QtCore.QRect(110, 300, 120, 40))
        self.labelOpenRangeHigh.setMinimumSize(QtCore.QSize(120, 40))
        self.labelOpenRangeHigh.setBaseSize(QtCore.QSize(120, 40))
        self.labelOpenRangeHigh.setObjectName("labelOpenRangeHigh")
        self.labelOpenRangeLow = QtWidgets.QLabel(self.tab)
        self.labelOpenRangeLow.setEnabled(True)
        self.labelOpenRangeLow.setGeometry(QtCore.QRect(390, 300, 120, 40))
        self.labelOpenRangeLow.setMinimumSize(QtCore.QSize(120, 40))
        self.labelOpenRangeLow.setBaseSize(QtCore.QSize(120, 40))
        self.labelOpenRangeLow.setObjectName("labelOpenRangeLow")
        self.lineEditOpenRangeLow = QtWidgets.QLineEdit(self.tab)
        self.lineEditOpenRangeLow.setEnabled(True)
        self.lineEditOpenRangeLow.setGeometry(QtCore.QRect(330, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOpenRangeLow.sizePolicy().hasHeightForWidth())
        self.lineEditOpenRangeLow.setSizePolicy(sizePolicy)
        self.lineEditOpenRangeLow.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditOpenRangeLow.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOpenRangeLow.setFont(font)
        self.lineEditOpenRangeLow.setText("")
        self.lineEditOpenRangeLow.setObjectName("lineEditOpenRangeLow")
        self.lineEditDailyPivotNumber = QtWidgets.QLineEdit(self.tab)
        self.lineEditDailyPivotNumber.setEnabled(True)
        self.lineEditDailyPivotNumber.setGeometry(QtCore.QRect(570, 340, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDailyPivotNumber.sizePolicy().hasHeightForWidth())
        self.lineEditDailyPivotNumber.setSizePolicy(sizePolicy)
        self.lineEditDailyPivotNumber.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditDailyPivotNumber.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditDailyPivotNumber.setFont(font)
        self.lineEditDailyPivotNumber.setText("")
        self.lineEditDailyPivotNumber.setObjectName("lineEditDailyPivotNumber")
        self.labelDailyPivotNumber = QtWidgets.QLabel(self.tab)
        self.labelDailyPivotNumber.setEnabled(True)
        self.labelDailyPivotNumber.setGeometry(QtCore.QRect(620, 300, 120, 40))
        self.labelDailyPivotNumber.setMinimumSize(QtCore.QSize(120, 40))
        self.labelDailyPivotNumber.setBaseSize(QtCore.QSize(120, 40))
        self.labelDailyPivotNumber.setObjectName("labelDailyPivotNumber")
        self.labelAup = QtWidgets.QLabel(self.tab)
        self.labelAup.setEnabled(True)
        self.labelAup.setGeometry(QtCore.QRect(130, 410, 120, 40))
        self.labelAup.setMinimumSize(QtCore.QSize(120, 40))
        self.labelAup.setBaseSize(QtCore.QSize(120, 40))
        self.labelAup.setObjectName("labelAup")
        self.lineEditAup = QtWidgets.QLineEdit(self.tab)
        self.lineEditAup.setEnabled(True)
        self.lineEditAup.setGeometry(QtCore.QRect(40, 440, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAup.sizePolicy().hasHeightForWidth())
        self.lineEditAup.setSizePolicy(sizePolicy)
        self.lineEditAup.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditAup.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAup.setFont(font)
        self.lineEditAup.setText("")
        self.lineEditAup.setObjectName("lineEditAup")
        self.labelAdwn = QtWidgets.QLabel(self.tab)
        self.labelAdwn.setEnabled(True)
        self.labelAdwn.setGeometry(QtCore.QRect(360, 410, 120, 40))
        self.labelAdwn.setMinimumSize(QtCore.QSize(120, 40))
        self.labelAdwn.setBaseSize(QtCore.QSize(120, 40))
        self.labelAdwn.setObjectName("labelAdwn")
        self.lineEditAdwn = QtWidgets.QLineEdit(self.tab)
        self.lineEditAdwn.setEnabled(True)
        self.lineEditAdwn.setGeometry(QtCore.QRect(330, 450, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAdwn.sizePolicy().hasHeightForWidth())
        self.lineEditAdwn.setSizePolicy(sizePolicy)
        self.lineEditAdwn.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditAdwn.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAdwn.setFont(font)
        self.lineEditAdwn.setText("")
        self.lineEditAdwn.setObjectName("lineEditAdwn")
        self.lineEditTone = QtWidgets.QLineEdit(self.tab)
        self.lineEditTone.setEnabled(True)
        self.lineEditTone.setGeometry(QtCore.QRect(570, 450, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTone.sizePolicy().hasHeightForWidth())
        self.lineEditTone.setSizePolicy(sizePolicy)
        self.lineEditTone.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditTone.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditTone.setFont(font)
        self.lineEditTone.setText("")
        self.lineEditTone.setObjectName("lineEditTone")
        self.labelTone = QtWidgets.QLabel(self.tab)
        self.labelTone.setEnabled(True)
        self.labelTone.setGeometry(QtCore.QRect(620, 410, 120, 40))
        self.labelTone.setMinimumSize(QtCore.QSize(120, 40))
        self.labelTone.setBaseSize(QtCore.QSize(120, 40))
        self.labelTone.setObjectName("labelTone")
        self.labelPivotRangeTop = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop.setEnabled(True)
        self.labelPivotRangeTop.setGeometry(QtCore.QRect(90, 500, 120, 40))
        self.labelPivotRangeTop.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop.setObjectName("labelPivotRangeTop")
        self.lineEditPivotRangeTop = QtWidgets.QLineEdit(self.tab)
        self.lineEditPivotRangeTop.setEnabled(True)
        self.lineEditPivotRangeTop.setGeometry(QtCore.QRect(40, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPivotRangeTop.sizePolicy().hasHeightForWidth())
        self.lineEditPivotRangeTop.setSizePolicy(sizePolicy)
        self.lineEditPivotRangeTop.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditPivotRangeTop.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPivotRangeTop.setFont(font)
        self.lineEditPivotRangeTop.setText("")
        self.lineEditPivotRangeTop.setObjectName("lineEditPivotRangeTop")
        self.labelPivotRangeBottom = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeBottom.setEnabled(True)
        self.labelPivotRangeBottom.setGeometry(QtCore.QRect(360, 510, 120, 40))
        self.labelPivotRangeBottom.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeBottom.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeBottom.setObjectName("labelPivotRangeBottom")
        self.lineEditPivotRangeBottom = QtWidgets.QLineEdit(self.tab)
        self.lineEditPivotRangeBottom.setEnabled(True)
        self.lineEditPivotRangeBottom.setGeometry(QtCore.QRect(330, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPivotRangeBottom.sizePolicy().hasHeightForWidth())
        self.lineEditPivotRangeBottom.setSizePolicy(sizePolicy)
        self.lineEditPivotRangeBottom.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditPivotRangeBottom.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPivotRangeBottom.setFont(font)
        self.lineEditPivotRangeBottom.setText("")
        self.lineEditPivotRangeBottom.setObjectName("lineEditPivotRangeBottom")
        self.lineEditLastOpen = QtWidgets.QLineEdit(self.tab)
        self.lineEditLastOpen.setEnabled(True)
        self.lineEditLastOpen.setGeometry(QtCore.QRect(40, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLastOpen.sizePolicy().hasHeightForWidth())
        self.lineEditLastOpen.setSizePolicy(sizePolicy)
        self.lineEditLastOpen.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditLastOpen.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLastOpen.setFont(font)
        self.lineEditLastOpen.setText("")
        self.lineEditLastOpen.setObjectName("lineEditLastOpen")
        self.lineEditLastClose = QtWidgets.QLineEdit(self.tab)
        self.lineEditLastClose.setEnabled(True)
        self.lineEditLastClose.setGeometry(QtCore.QRect(330, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLastClose.sizePolicy().hasHeightForWidth())
        self.lineEditLastClose.setSizePolicy(sizePolicy)
        self.lineEditLastClose.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditLastClose.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLastClose.setFont(font)
        self.lineEditLastClose.setText("")
        self.lineEditLastClose.setObjectName("lineEditLastClose")
        self.labelPivotRangeTop_2 = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop_2.setEnabled(True)
        self.labelPivotRangeTop_2.setGeometry(QtCore.QRect(90, 590, 120, 40))
        self.labelPivotRangeTop_2.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_2.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_2.setObjectName("labelPivotRangeTop_2")
        self.labelPivotRangeTop_3 = QtWidgets.QLabel(self.tab)
        self.labelPivotRangeTop_3.setEnabled(True)
        self.labelPivotRangeTop_3.setGeometry(QtCore.QRect(370, 590, 120, 40))
        self.labelPivotRangeTop_3.setMinimumSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_3.setBaseSize(QtCore.QSize(120, 40))
        self.labelPivotRangeTop_3.setObjectName("labelPivotRangeTop_3")
        self.lineEditMomentum = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentum.setEnabled(True)
        self.lineEditMomentum.setGeometry(QtCore.QRect(560, 550, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentum.sizePolicy().hasHeightForWidth())
        self.lineEditMomentum.setSizePolicy(sizePolicy)
        self.lineEditMomentum.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentum.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentum.setFont(font)
        self.lineEditMomentum.setText("")
        self.lineEditMomentum.setObjectName("lineEditMomentum")
        self.labelMomentum = QtWidgets.QLabel(self.tab)
        self.labelMomentum.setEnabled(True)
        self.labelMomentum.setGeometry(QtCore.QRect(620, 500, 120, 40))
        self.labelMomentum.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentum.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentum.setObjectName("labelMomentum")
        self.labelMomentumYesterday2 = QtWidgets.QLabel(self.tab)
        self.labelMomentumYesterday2.setEnabled(True)
        self.labelMomentumYesterday2.setGeometry(QtCore.QRect(620, 600, 120, 40))
        self.labelMomentumYesterday2.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday2.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday2.setObjectName("labelMomentumYesterday2")
        self.lineEditMomentumYesterday2 = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentumYesterday2.setEnabled(True)
        self.lineEditMomentumYesterday2.setGeometry(QtCore.QRect(560, 640, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentumYesterday2.sizePolicy().hasHeightForWidth())
        self.lineEditMomentumYesterday2.setSizePolicy(sizePolicy)
        self.lineEditMomentumYesterday2.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentumYesterday2.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentumYesterday2.setFont(font)
        self.lineEditMomentumYesterday2.setText("")
        self.lineEditMomentumYesterday2.setObjectName("lineEditMomentumYesterday2")
        self.labelMomentumYesterday3 = QtWidgets.QLabel(self.tab)
        self.labelMomentumYesterday3.setEnabled(True)
        self.labelMomentumYesterday3.setGeometry(QtCore.QRect(610, 690, 120, 40))
        self.labelMomentumYesterday3.setMinimumSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday3.setBaseSize(QtCore.QSize(120, 40))
        self.labelMomentumYesterday3.setObjectName("labelMomentumYesterday3")
        self.lineEditMomentumYesterday3 = QtWidgets.QLineEdit(self.tab)
        self.lineEditMomentumYesterday3.setEnabled(True)
        self.lineEditMomentumYesterday3.setGeometry(QtCore.QRect(560, 730, 203, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMomentumYesterday3.sizePolicy().hasHeightForWidth())
        self.lineEditMomentumYesterday3.setSizePolicy(sizePolicy)
        self.lineEditMomentumYesterday3.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditMomentumYesterday3.setBaseSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMomentumYesterday3.setFont(font)
        self.lineEditMomentumYesterday3.setText("")
        self.lineEditMomentumYesterday3.setObjectName("lineEditMomentumYesterday3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButtonACDgetshorts = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonACDgetshorts.setGeometry(QtCore.QRect(470, 40, 120, 48))
        self.pushButtonACDgetshorts.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetshorts.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetshorts.setObjectName("pushButtonACDgetshorts")
        self.pushButtonACDgetlongs = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonACDgetlongs.setGeometry(QtCore.QRect(100, 40, 120, 48))
        self.pushButtonACDgetlongs.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetlongs.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonACDgetlongs.setObjectName("pushButtonACDgetlongs")
        self.pushButtonAuplongs = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAuplongs.setGeometry(QtCore.QRect(100, 120, 120, 48))
        self.pushButtonAuplongs.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAuplongs.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAuplongs.setObjectName("pushButtonAuplongs")
        self.pushButtonAdwnshorts = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAdwnshorts.setGeometry(QtCore.QRect(470, 130, 120, 48))
        self.pushButtonAdwnshorts.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonAdwnshorts.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonAdwnshorts.setObjectName("pushButtonAdwnshorts")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButtonACD.clicked.connect(MainWindow.getACD)
        self.pushButtonACDgetshorts.clicked.connect(MainWindow.getminus4)
        self.pushButtonACDgetlongs.clicked.connect(MainWindow.getplus5)
        self.pushButtonAuplongs.clicked.connect(MainWindow.getauplong)
        self.pushButtonAdwnshorts.clicked.connect(MainWindow.getadwnshorts)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelStartDate.setText(_translate("MainWindow", "30 Days Ago "))
        self.labelTodayDate.setText(_translate("MainWindow", "Todays Date"))
        self.checkBoxToday.setText(_translate("MainWindow", "Today"))
        self.labelSymbol.setText(_translate("MainWindow", "Symbol"))
        self.labelYesterdayDate.setText(_translate("MainWindow", "Yesterday"))
        self.pushButtonACD.setText(_translate("MainWindow", "Get ACD"))
        self.labelOpenRangeHigh.setText(_translate("MainWindow", "Open Range High"))
        self.labelOpenRangeLow.setText(_translate("MainWindow", "Open Range Low"))
        self.labelDailyPivotNumber.setText(_translate("MainWindow", "Daily Pivot Number"))
        self.labelAup.setText(_translate("MainWindow", "A Up "))
        self.labelAdwn.setText(_translate("MainWindow", "A Down"))
        self.labelTone.setText(_translate("MainWindow", "Tone"))
        self.labelPivotRangeTop.setText(_translate("MainWindow", "Pivot Range Top"))
        self.labelPivotRangeBottom.setText(_translate("MainWindow", "Pivot Range Top"))
        self.labelPivotRangeTop_2.setText(_translate("MainWindow", "Last Open"))
        self.labelPivotRangeTop_3.setText(_translate("MainWindow", "Last Close"))
        self.labelMomentum.setText(_translate("MainWindow", "Momentum 1"))
        self.labelMomentumYesterday2.setText(_translate("MainWindow", "Momentum Yesterday 2"))
        self.labelMomentumYesterday3.setText(_translate("MainWindow", "Momentum Yesterday 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Daily ACD"))
        self.pushButtonACDgetshorts.setText(_translate("MainWindow", "9:50AM - Shorts"))
        self.pushButtonACDgetlongs.setText(_translate("MainWindow", "9:50AM - Longs"))
        self.pushButtonAuplongs.setText(_translate("MainWindow", "(min) A up A dwn"))
        self.pushButtonAdwnshorts.setText(_translate("MainWindow", "(min) A up A dwn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Market"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
